apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mq-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploymentname
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metricName: ibmmq_qdepth_queuename
      targetAverageValue: 10
